# Generated by Django 5.1.7 on 2025-10-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplaces",
            name="number",
            field=models.CharField(max_length=100, verbose_name="пол"),
        ),
        migrations.AlterField(
            model_name="workplaces",
            name="other",
            field=models.CharField(max_length=100, verbose_name="ФИО"),
        ),
    ]
