# Generated by Django 5.1.7 on 2025-10-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0002_alter_workplaces_number_alter_workplaces_other"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplaces",
            name="other",
            field=models.CharField(
                max_length=100, verbose_name="Дополнительная информация"
            ),
        ),
    ]
