# Generated by Django 5.1.7 on 2025-10-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0003_alter_workplaces_other"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workplaces",
            options={
                "verbose_name": "рабочее место",
                "verbose_name_plural": "Рабочие места",
            },
        ),
        migrations.AlterField(
            model_name="workplaces",
            name="number",
            field=models.CharField(max_length=100, verbose_name="Номер"),
        ),
    ]
