# Generated by Django 5.1.7 on 2025-10-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0004_alter_workplaces_options_alter_workplaces_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplaces",
            name="number",
            field=models.IntegerField(unique=True, verbose_name="Номер"),
        ),
    ]
