# Generated by Django 5.1.7 on 2025-10-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100, verbose_name='пол')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('skills', models.CharField(max_length=100, verbose_name='Навыки')),
                ('grade', models.CharField(max_length=10, verbose_name='Уровень освоения навыка')),
                ('discription', models.CharField(max_length=100, verbose_name='Описание')),
            ],
        ),
    ]
