# Generated by Django 5.1.7 on 2025-10-18 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0001_initial"),
        ("workplaces", "0002_alter_workplaces_number_alter_workplaces_other"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="workplace",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker",
                to="workplaces.workplaces",
            ),
        ),
    ]
