# Generated by Django 5.1.7 on 2025-10-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0002_worker_workplace"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "работник", "verbose_name_plural": "Работники"},
        ),
        migrations.AddField(
            model_name="worker",
            name="cover",
            field=models.ImageField(blank=True, upload_to="covers/"),
        ),
    ]
