# Generated by Django 5.1.7 on 2025-10-19 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0003_alter_worker_options_worker_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="cover",
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "worker",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="workers.worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение сотрудника",
                "verbose_name_plural": "Изображения сотрудника",
                "ordering": ["order"],
            },
        ),
    ]
