# Generated by Django 5.1.7 on 2025-10-19 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0004_remove_worker_cover_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="workers.worker",
            ),
        ),
    ]
