# Generated by Django 5.1.7 on 2025-10-20 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0005_alter_images_worker"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worker",
            old_name="discription",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="worker",
            name="grade",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Уровень освоения навыка",
            ),
        ),
    ]
