# Generated by Django 5.1.7 on 2025-10-20 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0006_rename_discription_worker_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="grade",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Уровень освоения навыка",
            ),
        ),
    ]
