# Generated by Django 5.1.7 on 2025-10-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0007_alter_worker_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="hire_date",
            field=models.DateField(
                blank=True,
                max_length=11,
                null=True,
                verbose_name="Дата приёма на работу",
            ),
        ),
    ]
