# Generated by Django 5.1.7 on 2025-10-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0008_worker_hire_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="hire_date",
        ),
        migrations.AddField(
            model_name="worker",
            name="date_of_joining",
            field=models.DateField(blank=True, null=True, verbose_name="Дата приема"),
        ),
    ]
