# Generated by Django 5.1.7 on 2025-10-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0009_remove_worker_hire_date_worker_date_of_joining"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="skills",
            field=models.CharField(
                choices=[
                    ("developer", "Бекендер"),
                    ("tester", "Тестировщик"),
                    ("developer", "Фротендер"),
                    ("other", "Другой"),
                ],
                max_length=100,
                verbose_name="Навыки",
            ),
        ),
    ]
