# Generated by Django 5.1.7 on 2025-10-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0010_alter_worker_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="skills",
            field=models.CharField(max_length=100, verbose_name="Навыки"),
        ),
    ]
